services:
  - type: web
    name: mylucky2d3d
    env: node
    region: oregon
    plan: free
    buildCommand: |
      npm install
      npx puppeteer browsers install chrome || echo "Puppeteer Chrome install skipped"
    startCommand: node server.js
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/.cache/puppeteer/chrome/linux-142.0.7444.59/chrome-linux64/chrome
    disk:
      name: puppeteer-cache
      mountPath: /opt/render/.cache/puppeteer
      sizeGB: 1
